DECLARE @date DATE
SET @date = DATEADD(mm, -6, GETDATE())
DECLARE @dateDay DATE
SET @dateDay = CAST(GETDATE() AS DATE)
IF((SELECT COUNT(*) FROM SYS.SYSVIEWS WHERE VIEWNAME = 'DC_E_NR_NRCELLDU_DAY') > 0 )
SELECT
DATE_ID,
NR_NAME,
SUM(0.008*pmMacVolDl) AS DataVolumeDown,
SUM(0.008*pmMacVolUl) AS DataVolumeUp,
'5G' AS NODE_TYPE
FROM DC_E_NR_NRCELLDU_DAY
WHERE DATE_ID >= @date AND DATE_ID < @dateDay 
GROUP BY DATE_ID,NR_NAME
ELSE
SELECT
	NULL AS "DATE_ID", 
 	NULL AS "DataVolumeDown", 
 	NULL AS "DataVolumeUp", 
 	NULL AS "NODE_TYPE"